# Generated by Django 5.2.7 on 2025-11-03 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_borrow_return_date_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 10, 13, 5, 48, 313311, tzinfo=datetime.timezone.utc)),
        ),
    ]
