# Generated by Django 5.2.7 on 2025-11-03 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_borrow_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 10, 14, 0, 54, 337309, tzinfo=datetime.timezone.utc)),
        ),
    ]
